# Use root/example as user/password credentials
version: '3'

services:
    backendapi:
        image: karpiu/homebrewing-storage-api
        restart: always
        container_name: Backend_API
        depends_on:
            - db
        environment:
            DBServer: Database
            DBPort: 1433
            DBUser: SA
            DBPassword: ThisIsNotSuperSecretP@55w0rd
            Database: Backend_API
            SmtpServer: test.test
            SmtpPort: 123
            SSL: "True"
            SmtpUserName: testusername
            SmtpUserPassword: testpassword
        ports: 
            - "8080:80"
    db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        restart: always
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: ThisIsNotSuperSecretP@55w0rd
            MSSQL_PID: Express
        container_name: Database
        ports: 
            - "14331:1433"            