# Use root/example as user/password credentials
version: '3'

services:
    frontend:
        image: karpiu/homebrewing-storage-frontend
        restart: always
        container_name: Frontend
        ports: 
            - "3000:3000"