# Use root/example as user/password credentials
version: '3'

services:
    frontend:
        build:
            context: Frontend/
        restart: always
        container_name: Frontend_DEV
        ports: 
            - "3000:3000"