name: Backend CI
env:
  DBServer: 0.0.0.0
  DBPort: 14331
  DBUser: SA
  DBPassword: ThisIsNotSuperSecretP@55w0rd
  Database: Backend_API
  SmtpServer: smtp.email.email
  SmtpPort: 465
  SSL: "True"
  SmtpUserName: email@emauil.email
  SmtpUserPassword: password
  NotificationSchedule: "0 0 3 * * ?"

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
            ACCEPT_EULA: Y
            SA_PASSWORD: ThisIsNotSuperSecretP@55w0rd
            MSSQL_PID: Express
        ports: 
            - "14331:1433"            
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
