name: Backend CI
env:
  DBServer: Database
  DBPort: 1433
  DBUser: SA
  DBPassword: ThisIsNotSuperSecretP@55w0rd
  Database: Test_Backend_API

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      Database:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
          - 1433
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: ThisIsNotSuperSecretP@55w0rd
          MSSQL_PID: Express
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
